openapi: 3.0.0
info:
  version: 1.0.0
  title: Bankown API
  description: Bankown
servers:
  - url: http://127.0.0.1:8000/api
    description: Local server
  - url: https://bankown.mutad.ml/api
    description: Production server

paths:
  /status:
    get:
      tags:
        - server
      operationId: GetServerStatus
      summary: Get the current server status
      description: Returns server status

      responses:
        "200":
          description: Server status is ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/serverResponse"
              example: { "message": "ok" }

  /auth/login:
    post:
      tags:
        - authentication
      operationId: Login
      summary: Login endpoint
      description: Login by email and password

      requestBody:
        description: Auth fields
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/authFields"
            example: { "email": "mutado.nzr@gmail.com", "password": "12345678" }

      responses:
        "200":
          description: Successfully logged in
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/authResponse"

        "422":
          description: Validation error
        "401":
          description: Wrong login or password

        "default":
          description: Error
  /auth/register:
    post:
      tags:
        - authentication
      operationId: Register
      summary: Register endpoint
      description: Register a new user

      requestBody:
        description: New User data
        required: true
        content:
          application/json:
            schema:
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                country:
                  type: string
                birth_date:
                  type: string
                  description: DD/MM/YYYY
                email:
                  type: string
                  description: email of this user
                password:
                  type: string
                password_repeat:
                  type: string
            example:
              {
                "first_name": "Nazar",
                "last_name": "Potipaka",
                "country": "United States",
                "birth_date": "11/09/2002",
                "email": "mutado.nzr@gmail.com",
                "password": "12345678",
                "password_repeat": "12345678",
              }

      responses:
        "201":
          description: Successfully registered
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/authResponse"
        "422":
          description: Validation error

  /auth/user:
    get:
      tags:
        - authentication
      summary: Get authenticated user
      operationId: getUser

      security:
        - bearerAuth: []

      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        "401":
          description: Unauthenticated
  /cards:
    get:
      tags:
        - card
      summary: Get all cards
      description: Returns an array of cards
      operationId: getCard

      security:
        - bearerAuth: []

      responses:
        "200":
          description: Array of cards
          content:
            application:json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/card"
    post:
      tags:
        - card
      summary: Create a new card
      description: Create a fresh card for this user
      operationId: postCard

      security:
        - bearerAuth: []

      requestBody:
        description: Card props
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
                currency:
                  type: string
                user_id:
                  type: integer
                type:
                  type: string
            example:
              {
                "name": "Card for payments",
                "currency": "USD",
                "user_id": "1",
                "type": "DEBIT",
              }

      responses:
        "201":
          description: Fresh new card
          content:
            application:json:
              schema:
                $ref: "#/components/schemas/card"
  /cards/{cardId}:
    put:
      tags:
        - card
      summary: Update card
      description: Update card name
      operationId: updateCard

      security:
        - bearerAuth: []

      parameters:
        - name: cardId
          in: path
          required: true
          description: Unique card id
          schema:
            type: integer
            format: int64
            minimum: 1
      requestBody:
        description: Card props
        required: true
        content:
          application/json:
            schema:
              properties:
                name:
                  type: string
            example: { "name": "Card for payments" }

      responses:
        "200":
          description: Your updated card
          content:
            application:json:
              schema:
                $ref: "#/components/schemas/card"

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    serverResponse:
      type: object
      properties:
        message:
          type: string
    authFields:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    user:
      type: object
      properties:
        id:
          type: integer
          description: unique id of user
        first_name:
          type: string
        last_name:
          type: string
        country:
          type: string
        birth_date:
          type: string
        email:
          type: string
          description: email of this user
    card:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        balance:
          type: number
        currency:
          type: string
        user_id:
          type: integer
        type:
          type: string
        number:
          type: string

    authResponse:
      type: object
      properties:
        access_token:
          type: string
          description: Personal Access Token
        token_type:
          type: string
          description: Type of Personal Access Token
        expires_at:
          type: string
          description: Time of Token expiration
        user:
          $ref: "#/components/schemas/user"
